{
 "title": "Nmap Dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Hosts Up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT COUNT(DISTINCT ip) AS count\nFROM hosts\nWHERE start_time >= $__from AND end_time <= $__to;\n",
     "rawQueryText": "SELECT COUNT(DISTINCT ip) AS count\nFROM hosts\nWHERE start_time >= $__from AND end_time <= $__to;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Operating Systems",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "    \nSELECT\n  os,\n  COUNT(*) AS \"count\"\nFROM hosts\nWHERE start_time >= $__from AND end_time < $__to\nGROUP BY os\nORDER BY count DESC;\n\n    \n",
     "rawQueryText": "    \nSELECT\n  os,\n  COUNT(*) AS \"count\"\nFROM hosts\nWHERE start_time >= $__from AND end_time < $__to\nGROUP BY os\nORDER BY count DESC;\n\n    \n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Unidentified Services (open port)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT p.port, COUNT(*) AS count\nFROM ports p\nJOIN hosts h ON p.host_id = h.id\nWHERE h.start_time >= $__from AND h.end_time < $__to\n AND p.service_info = '' AND p.state = 'open'\nGROUP BY p.port",
     "rawQueryText": "SELECT p.port, COUNT(*) AS count\nFROM ports p\nJOIN hosts h ON p.host_id = h.id\nWHERE h.start_time >= $__from AND h.end_time < $__to\n AND p.service_info = '' AND p.state = 'open'\nGROUP BY p.port",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Identified Services",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT p.service_info, COUNT(*) AS count\nFROM ports p\nJOIN hosts h ON p.host_id = h.id\nWHERE h.start_time >= $__from AND h.end_time < $__to\nAND p.service_info IS NOT NULL AND p.service_info <> ''\nGROUP BY p.service_info\n",
     "rawQueryText": "SELECT p.service_info, COUNT(*) AS count\nFROM ports p\nJOIN hosts h ON p.host_id = h.id\nWHERE h.start_time >= $__from AND h.end_time < $__to\nAND p.service_info IS NOT NULL AND p.service_info <> ''\nGROUP BY p.service_info\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Open Ports",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT SUM(unique_open_ports) AS total_unique_open_ports\nFROM (\n  SELECT\n    COUNT(DISTINCT p.port) AS unique_open_ports,\n    h.ip AS host_ip\n  FROM ports p\n  JOIN hosts h ON p.host_id = h.id\n  WHERE p.state = 'open' AND h.start_time >= $__from AND h.end_time < $__to\n  GROUP BY h.ip, p.port\n) AS subquery;\n    ",
     "rawQueryText": "SELECT SUM(unique_open_ports) AS total_unique_open_ports\nFROM (\n  SELECT\n    COUNT(DISTINCT p.port) AS unique_open_ports,\n    h.ip AS host_ip\n  FROM ports p\n  JOIN hosts h ON p.host_id = h.id\n  WHERE p.state = 'open' AND h.start_time >= $__from AND h.end_time < $__to\n  GROUP BY h.ip, p.port\n) AS subquery;\n    ",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Unique Ports",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  COUNT(DISTINCT p.port) AS \"Unique Ports\"\nFROM ports p\nJOIN hosts h ON p.host_id = h.id\nWHERE h.start_time >= $__from AND h.end_time < $__to AND p.state is 'open'\n",
     "rawQueryText": "SELECT\n  COUNT(DISTINCT p.port) AS \"Unique Ports\"\nFROM ports p\nJOIN hosts h ON p.host_id = h.id\nWHERE h.start_time >= $__from AND h.end_time < $__to AND p.state is 'open'\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Open Ports Found",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 10, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "SELECT\n  p.port,\n  COUNT(DISTINCT h.ip) AS host_count\nFROM\n  hosts h\n  JOIN ports p ON h.id = p.host_id\nWHERE\n  p.state = 'open' AND h.start_time >= $__from AND h.end_time < $__to\nGROUP BY\n  p.port;",
     "rawQueryText": "SELECT\n  p.port,\n  COUNT(DISTINCT h.ip) AS host_count\nFROM\n  hosts h\n  JOIN ports p ON h.id = p.host_id\nWHERE\n  p.state = 'open' AND h.start_time >= $__from AND h.end_time < $__to\nGROUP BY\n  p.port;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Scans",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  COUNT(*) AS count\nFROM scans\nWHERE\n  start_time >= $__from / 1000\n  AND start_time + elapsed_time < $__to / 1000",
     "rawQueryText": "SELECT\n  COUNT(*) AS count\nFROM scans\nWHERE\n  start_time >= $__from / 1000\n  AND start_time + elapsed_time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Hosts",
   "type": "table",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 12 },
   "targets": [
    {
     "queryText": "SELECT ip, hostname, ports_tested, ports_open, ports_closed, ports_filtered FROM hosts\nWHERE start_time >= $__from AND end_time < $__to",
     "rawQueryText": "SELECT ip, hostname, ports_tested, ports_open, ports_closed, ports_filtered FROM hosts\nWHERE start_time >= $__from AND end_time < $__to",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Live Hosts and Open Ports over Time",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 12 },
   "targets": [
    {
     "queryText": "SELECT\n  start_time AS \"time\",\n  total_open_ports AS \"open_ports\",\n  total_hosts\nFROM scans\nWHERE\n  start_time >= $__from / 1000\n  AND start_time + elapsed_time < $__to / 1000\nORDER BY start_time",
     "rawQueryText": "SELECT\n  start_time AS \"time\",\n  total_open_ports AS \"open_ports\",\n  total_hosts\nFROM scans\nWHERE\n  start_time >= $__from / 1000\n  AND start_time + elapsed_time < $__to / 1000\nORDER BY start_time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Port Tested Per Second by Host",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 16 },
   "targets": [
    {
     "queryText": "SELECT ip, \n       (ports_tested * 1.0) / ((end_time - start_time) / 1000) AS avg_ports_per_second\nFROM hosts\nWHERE start_time >= $__from AND end_time < $__to AND ports_tested IS NOT NULL\nORDER BY ip;",
     "rawQueryText": "SELECT ip, \n       (ports_tested * 1.0) / ((end_time - start_time) / 1000) AS avg_ports_per_second\nFROM hosts\nWHERE start_time >= $__from AND end_time < $__to AND ports_tested IS NOT NULL\nORDER BY ip;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Open Services",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "queryText": "SELECT h.ip, p.protocol, p.port, p.service_info, p.http_title, p.http_headers, p.cpes, p.exploit\nFROM ports p\nJOIN hosts h ON p.host_id = h.id\nWHERE h.start_time >= 1751492729108 AND h.end_time < 1754084729108\nAND p.state = 'open'\n",
     "rawQueryText": "SELECT h.ip, p.protocol, p.port, p.service_info, p.http_title, p.http_headers, p.cpes, p.exploit\nFROM ports p\nJOIN hosts h ON p.host_id = h.id\nWHERE h.start_time >= $__from AND h.end_time < $__to\nAND p.state = 'open'\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Scans Loaded",
   "type": "table",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 41 },
   "targets": [
    {
     "queryText": "SELECT\n  datetime(start_time, 'unixepoch') AS start_time_utc,\n  nmap_version,\n  command_line,\n  elapsed_time,\n  total_hosts,\n  total_open_ports\nFROM scans\nWHERE\n  start_time >= $__from / 1000\n  AND start_time + elapsed_time < $__to / 1000",
     "rawQueryText": "SELECT\n  datetime(start_time, 'unixepoch') AS start_time_utc,\n  nmap_version,\n  command_line,\n  elapsed_time,\n  total_hosts,\n  total_open_ports\nFROM scans\nWHERE\n  start_time >= $__from / 1000\n  AND start_time + elapsed_time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}